### ISSUE TITLE
Player Side - Master issue

### ISSUE THREAD

**Issue by pldespaigne** [blockframes/nft#1]
> This is the master issue that sums up everything there to do to finish the player side of the app.

**Feel free to add or modify the issues**

## High level overview
- [x] install ethers and setup a service along with a connect/login guard @phpgeekfr 
- [x] setup jwplayer backend along with a dummy player and movie @pldespaigne 
- [x] implement sign message logic in front-end & integrate verify to the jwplayer backend
- [x] implement inventory page

## Wireframes
1) `/connect`
![image](https://user-images.githubusercontent.com/5858657/114558351-e0634280-9c6a-11eb-8106-bbdaee5e88bf.png)

2) `/inventory`
![image](https://user-images.githubusercontent.com/5858657/114558688-3c2dcb80-9c6b-11eb-9005-3524257d5891.png)

3) `/watch/<TOKEN_ID>`
    - 1 sign message
![image](https://user-images.githubusercontent.com/5858657/114558796-5667a980-9c6b-11eb-9de7-2adf0f909100.png)

    - 2 watch movie
![image](https://user-images.githubusercontent.com/5858657/114558846-61bad500-9c6b-11eb-9856-c6c6ebe793bc.png)
